language: python
python:
  - "3.6"
notifications:
  email: false

install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -U nltk

script:
  - py.test

after_success:
  - coveralls
